micronaut:
  application:
    name: mnPokemonTcg
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:changeThisSecretToALongStringNotEnough}
liquibase:
  datasources:
    default:
      enabled: true
      change-log: 'classpath:db/liquibase-changelog.yml'
      drop-first: true
      default-schema: public
netty:
  default:
    allocator:
      max-order: 3

datasources:
  default:
    enabled: true
    clean-schema: true
    url: ${PG_JDBC_URL:`jdbc:postgresql://127.0.0.1:5432/mn-pokemon-tcg`}
    username: ${PG_USERNAME:postgres}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver
    schema-generate: NONE
    dialect: POSTGRES
#micronaut-data-jpa
jpa:
  default:
    packages-to-scan:
      - "io.github.fermarcgom.persistence"
    properties:
      hibernate:
        show-sql: false
        default-schema: pokemon_tcg
